version: "3.7"
services:
  client-server:
    image: kooldev/node:18
    command: ["node", "client-server/index.js"]
    ports:
      - "${KOOL_CLIENT_SERVER_PORT:-80}:80"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  game-server:
    image: kooldev/node:18
    command: ["node", "game-server/index.js"]
    ports:
      - "${KOOL_GAME_SERVER_PORT:-81}:81"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  data-server:
    image: kooldev/node:18
    command: ["node", "data-server/index.js"]
    ports:
      - "${KOOL_DATA_SERVER_PORT:-82}:82"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
