version: "3.7"
services:
  clientserver:
    image: kooldev/node:18
    command: ["npm", "--prefix", "./apps/clientserver", "run", "start:dev"]
    ports:
      - "${KOOL_CLIENTSERVER_PORT:-80}:80"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
      KOOL_APP_PORT: "${KOOL_CLIENTSERVER_PORT:-80}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  dataserver:
    image: kooldev/node:18
    command: ["npm", "--prefix", "./apps/dataserver", "run", "start:dev"]
    ports:
      - "${KOOL_DATASERVER_PORT:-81}:81"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
      KOOL_APP_PORT: "${KOOL_DATASERVER_PORT:-81}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  database:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${KOOL_DATABASE_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${KOOL_DATABASE_PASSWORD-rootpass}"
      MYSQL_DATABASE: "${KOOL_DATABASE_NAME-database}"
      MYSQL_USER: "${KOOL_DATABASE_USERNAME-user}"
      MYSQL_PASSWORD: "${KOOL_DATABASE_PASSWORD-pass}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - database:/var/lib/mysql:delegated
    networks:
      - kool_local
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
  database:
